// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types_test.proto

package protoid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestEnum int32

const (
	TestEnum_VAL_0 TestEnum = 0
	TestEnum_VAL_1 TestEnum = 1
)

var TestEnum_name = map[int32]string{
	0: "VAL_0",
	1: "VAL_1",
}
var TestEnum_value = map[string]int32{
	"VAL_0": 0,
	"VAL_1": 1,
}

func (x TestEnum) String() string {
	return proto.EnumName(TestEnum_name, int32(x))
}
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{0}
}

type SingleString struct {
	TheString            string   `protobuf:"bytes,1,opt,name=the_string,json=theString" json:"the_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleString) Reset()         { *m = SingleString{} }
func (m *SingleString) String() string { return proto.CompactTextString(m) }
func (*SingleString) ProtoMessage()    {}
func (*SingleString) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{0}
}
func (m *SingleString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleString.Unmarshal(m, b)
}
func (m *SingleString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleString.Marshal(b, m, deterministic)
}
func (dst *SingleString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleString.Merge(dst, src)
}
func (m *SingleString) XXX_Size() int {
	return xxx_messageInfo_SingleString.Size(m)
}
func (m *SingleString) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleString.DiscardUnknown(m)
}

var xxx_messageInfo_SingleString proto.InternalMessageInfo

func (m *SingleString) GetTheString() string {
	if m != nil {
		return m.TheString
	}
	return ""
}

type TwoStrings struct {
	String_1             string   `protobuf:"bytes,1,opt,name=string_1,json=string1" json:"string_1,omitempty"`
	String_2             string   `protobuf:"bytes,2,opt,name=string_2,json=string2" json:"string_2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoStrings) Reset()         { *m = TwoStrings{} }
func (m *TwoStrings) String() string { return proto.CompactTextString(m) }
func (*TwoStrings) ProtoMessage()    {}
func (*TwoStrings) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{1}
}
func (m *TwoStrings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoStrings.Unmarshal(m, b)
}
func (m *TwoStrings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoStrings.Marshal(b, m, deterministic)
}
func (dst *TwoStrings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoStrings.Merge(dst, src)
}
func (m *TwoStrings) XXX_Size() int {
	return xxx_messageInfo_TwoStrings.Size(m)
}
func (m *TwoStrings) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoStrings.DiscardUnknown(m)
}

var xxx_messageInfo_TwoStrings proto.InternalMessageInfo

func (m *TwoStrings) GetString_1() string {
	if m != nil {
		return m.String_1
	}
	return ""
}

func (m *TwoStrings) GetString_2() string {
	if m != nil {
		return m.String_2
	}
	return ""
}

type SingleInt32 struct {
	TheInt32             int32    `protobuf:"varint,1,opt,name=the_int32,json=theInt32" json:"the_int32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleInt32) Reset()         { *m = SingleInt32{} }
func (m *SingleInt32) String() string { return proto.CompactTextString(m) }
func (*SingleInt32) ProtoMessage()    {}
func (*SingleInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{2}
}
func (m *SingleInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleInt32.Unmarshal(m, b)
}
func (m *SingleInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleInt32.Marshal(b, m, deterministic)
}
func (dst *SingleInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleInt32.Merge(dst, src)
}
func (m *SingleInt32) XXX_Size() int {
	return xxx_messageInfo_SingleInt32.Size(m)
}
func (m *SingleInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleInt32.DiscardUnknown(m)
}

var xxx_messageInfo_SingleInt32 proto.InternalMessageInfo

func (m *SingleInt32) GetTheInt32() int32 {
	if m != nil {
		return m.TheInt32
	}
	return 0
}

type SingleBool struct {
	TheBool              bool     `protobuf:"varint,1,opt,name=the_bool,json=theBool" json:"the_bool,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleBool) Reset()         { *m = SingleBool{} }
func (m *SingleBool) String() string { return proto.CompactTextString(m) }
func (*SingleBool) ProtoMessage()    {}
func (*SingleBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{3}
}
func (m *SingleBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleBool.Unmarshal(m, b)
}
func (m *SingleBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleBool.Marshal(b, m, deterministic)
}
func (dst *SingleBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleBool.Merge(dst, src)
}
func (m *SingleBool) XXX_Size() int {
	return xxx_messageInfo_SingleBool.Size(m)
}
func (m *SingleBool) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleBool.DiscardUnknown(m)
}

var xxx_messageInfo_SingleBool proto.InternalMessageInfo

func (m *SingleBool) GetTheBool() bool {
	if m != nil {
		return m.TheBool
	}
	return false
}

type SingleFixed32 struct {
	TheFixed32           uint32   `protobuf:"fixed32,1,opt,name=the_fixed32,json=theFixed32" json:"the_fixed32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleFixed32) Reset()         { *m = SingleFixed32{} }
func (m *SingleFixed32) String() string { return proto.CompactTextString(m) }
func (*SingleFixed32) ProtoMessage()    {}
func (*SingleFixed32) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{4}
}
func (m *SingleFixed32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleFixed32.Unmarshal(m, b)
}
func (m *SingleFixed32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleFixed32.Marshal(b, m, deterministic)
}
func (dst *SingleFixed32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleFixed32.Merge(dst, src)
}
func (m *SingleFixed32) XXX_Size() int {
	return xxx_messageInfo_SingleFixed32.Size(m)
}
func (m *SingleFixed32) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleFixed32.DiscardUnknown(m)
}

var xxx_messageInfo_SingleFixed32 proto.InternalMessageInfo

func (m *SingleFixed32) GetTheFixed32() uint32 {
	if m != nil {
		return m.TheFixed32
	}
	return 0
}

type SingleFixed64 struct {
	TheFixed64           uint64   `protobuf:"fixed64,1,opt,name=the_fixed64,json=theFixed64" json:"the_fixed64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleFixed64) Reset()         { *m = SingleFixed64{} }
func (m *SingleFixed64) String() string { return proto.CompactTextString(m) }
func (*SingleFixed64) ProtoMessage()    {}
func (*SingleFixed64) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{5}
}
func (m *SingleFixed64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleFixed64.Unmarshal(m, b)
}
func (m *SingleFixed64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleFixed64.Marshal(b, m, deterministic)
}
func (dst *SingleFixed64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleFixed64.Merge(dst, src)
}
func (m *SingleFixed64) XXX_Size() int {
	return xxx_messageInfo_SingleFixed64.Size(m)
}
func (m *SingleFixed64) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleFixed64.DiscardUnknown(m)
}

var xxx_messageInfo_SingleFixed64 proto.InternalMessageInfo

func (m *SingleFixed64) GetTheFixed64() uint64 {
	if m != nil {
		return m.TheFixed64
	}
	return 0
}

type RepeatedString struct {
	MyString             []string `protobuf:"bytes,1,rep,name=my_string,json=myString" json:"my_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedString) Reset()         { *m = RepeatedString{} }
func (m *RepeatedString) String() string { return proto.CompactTextString(m) }
func (*RepeatedString) ProtoMessage()    {}
func (*RepeatedString) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{6}
}
func (m *RepeatedString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedString.Unmarshal(m, b)
}
func (m *RepeatedString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedString.Marshal(b, m, deterministic)
}
func (dst *RepeatedString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedString.Merge(dst, src)
}
func (m *RepeatedString) XXX_Size() int {
	return xxx_messageInfo_RepeatedString.Size(m)
}
func (m *RepeatedString) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedString.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedString proto.InternalMessageInfo

func (m *RepeatedString) GetMyString() []string {
	if m != nil {
		return m.MyString
	}
	return nil
}

type RepeatedInt32 struct {
	MyInt32S             []int32  `protobuf:"varint,1,rep,packed,name=my_int32s,json=myInt32s" json:"my_int32s,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedInt32) Reset()         { *m = RepeatedInt32{} }
func (m *RepeatedInt32) String() string { return proto.CompactTextString(m) }
func (*RepeatedInt32) ProtoMessage()    {}
func (*RepeatedInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{7}
}
func (m *RepeatedInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedInt32.Unmarshal(m, b)
}
func (m *RepeatedInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedInt32.Marshal(b, m, deterministic)
}
func (dst *RepeatedInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedInt32.Merge(dst, src)
}
func (m *RepeatedInt32) XXX_Size() int {
	return xxx_messageInfo_RepeatedInt32.Size(m)
}
func (m *RepeatedInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedInt32.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedInt32 proto.InternalMessageInfo

func (m *RepeatedInt32) GetMyInt32S() []int32 {
	if m != nil {
		return m.MyInt32S
	}
	return nil
}

type SingleEnum struct {
	TheEnum              TestEnum `protobuf:"varint,1,opt,name=the_enum,json=theEnum,enum=protoid.TestEnum" json:"the_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleEnum) Reset()         { *m = SingleEnum{} }
func (m *SingleEnum) String() string { return proto.CompactTextString(m) }
func (*SingleEnum) ProtoMessage()    {}
func (*SingleEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{8}
}
func (m *SingleEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleEnum.Unmarshal(m, b)
}
func (m *SingleEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleEnum.Marshal(b, m, deterministic)
}
func (dst *SingleEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleEnum.Merge(dst, src)
}
func (m *SingleEnum) XXX_Size() int {
	return xxx_messageInfo_SingleEnum.Size(m)
}
func (m *SingleEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleEnum.DiscardUnknown(m)
}

var xxx_messageInfo_SingleEnum proto.InternalMessageInfo

func (m *SingleEnum) GetTheEnum() TestEnum {
	if m != nil {
		return m.TheEnum
	}
	return TestEnum_VAL_0
}

type RepeatedEnum struct {
	TheEnums             TestEnum `protobuf:"varint,1,opt,name=the_enums,json=theEnums,enum=protoid.TestEnum" json:"the_enums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedEnum) Reset()         { *m = RepeatedEnum{} }
func (m *RepeatedEnum) String() string { return proto.CompactTextString(m) }
func (*RepeatedEnum) ProtoMessage()    {}
func (*RepeatedEnum) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{9}
}
func (m *RepeatedEnum) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedEnum.Unmarshal(m, b)
}
func (m *RepeatedEnum) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedEnum.Marshal(b, m, deterministic)
}
func (dst *RepeatedEnum) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedEnum.Merge(dst, src)
}
func (m *RepeatedEnum) XXX_Size() int {
	return xxx_messageInfo_RepeatedEnum.Size(m)
}
func (m *RepeatedEnum) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedEnum.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedEnum proto.InternalMessageInfo

func (m *RepeatedEnum) GetTheEnums() TestEnum {
	if m != nil {
		return m.TheEnums
	}
	return TestEnum_VAL_0
}

type SingleEmbedded struct {
	MySingleString       *SingleString `protobuf:"bytes,1,opt,name=my_single_string,json=mySingleString" json:"my_single_string,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SingleEmbedded) Reset()         { *m = SingleEmbedded{} }
func (m *SingleEmbedded) String() string { return proto.CompactTextString(m) }
func (*SingleEmbedded) ProtoMessage()    {}
func (*SingleEmbedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{10}
}
func (m *SingleEmbedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleEmbedded.Unmarshal(m, b)
}
func (m *SingleEmbedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleEmbedded.Marshal(b, m, deterministic)
}
func (dst *SingleEmbedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleEmbedded.Merge(dst, src)
}
func (m *SingleEmbedded) XXX_Size() int {
	return xxx_messageInfo_SingleEmbedded.Size(m)
}
func (m *SingleEmbedded) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleEmbedded.DiscardUnknown(m)
}

var xxx_messageInfo_SingleEmbedded proto.InternalMessageInfo

func (m *SingleEmbedded) GetMySingleString() *SingleString {
	if m != nil {
		return m.MySingleString
	}
	return nil
}

type RepeatedEmbedded struct {
	MySingleStrings      []*SingleString `protobuf:"bytes,1,rep,name=my_single_strings,json=mySingleStrings" json:"my_single_strings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RepeatedEmbedded) Reset()         { *m = RepeatedEmbedded{} }
func (m *RepeatedEmbedded) String() string { return proto.CompactTextString(m) }
func (*RepeatedEmbedded) ProtoMessage()    {}
func (*RepeatedEmbedded) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{11}
}
func (m *RepeatedEmbedded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedEmbedded.Unmarshal(m, b)
}
func (m *RepeatedEmbedded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedEmbedded.Marshal(b, m, deterministic)
}
func (dst *RepeatedEmbedded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedEmbedded.Merge(dst, src)
}
func (m *RepeatedEmbedded) XXX_Size() int {
	return xxx_messageInfo_RepeatedEmbedded.Size(m)
}
func (m *RepeatedEmbedded) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedEmbedded.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedEmbedded proto.InternalMessageInfo

func (m *RepeatedEmbedded) GetMySingleStrings() []*SingleString {
	if m != nil {
		return m.MySingleStrings
	}
	return nil
}

type SingleBytes struct {
	TheBytes             []byte   `protobuf:"bytes,1,opt,name=the_bytes,json=theBytes,proto3" json:"the_bytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleBytes) Reset()         { *m = SingleBytes{} }
func (m *SingleBytes) String() string { return proto.CompactTextString(m) }
func (*SingleBytes) ProtoMessage()    {}
func (*SingleBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_test_90bf5b8a360ba076, []int{12}
}
func (m *SingleBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleBytes.Unmarshal(m, b)
}
func (m *SingleBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleBytes.Marshal(b, m, deterministic)
}
func (dst *SingleBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleBytes.Merge(dst, src)
}
func (m *SingleBytes) XXX_Size() int {
	return xxx_messageInfo_SingleBytes.Size(m)
}
func (m *SingleBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleBytes.DiscardUnknown(m)
}

var xxx_messageInfo_SingleBytes proto.InternalMessageInfo

func (m *SingleBytes) GetTheBytes() []byte {
	if m != nil {
		return m.TheBytes
	}
	return nil
}

func init() {
	proto.RegisterType((*SingleString)(nil), "protoid.SingleString")
	proto.RegisterType((*TwoStrings)(nil), "protoid.TwoStrings")
	proto.RegisterType((*SingleInt32)(nil), "protoid.SingleInt32")
	proto.RegisterType((*SingleBool)(nil), "protoid.SingleBool")
	proto.RegisterType((*SingleFixed32)(nil), "protoid.SingleFixed32")
	proto.RegisterType((*SingleFixed64)(nil), "protoid.SingleFixed64")
	proto.RegisterType((*RepeatedString)(nil), "protoid.RepeatedString")
	proto.RegisterType((*RepeatedInt32)(nil), "protoid.RepeatedInt32")
	proto.RegisterType((*SingleEnum)(nil), "protoid.SingleEnum")
	proto.RegisterType((*RepeatedEnum)(nil), "protoid.RepeatedEnum")
	proto.RegisterType((*SingleEmbedded)(nil), "protoid.SingleEmbedded")
	proto.RegisterType((*RepeatedEmbedded)(nil), "protoid.RepeatedEmbedded")
	proto.RegisterType((*SingleBytes)(nil), "protoid.SingleBytes")
	proto.RegisterEnum("protoid.TestEnum", TestEnum_name, TestEnum_value)
}

func init() { proto.RegisterFile("types_test.proto", fileDescriptor_types_test_90bf5b8a360ba076) }

var fileDescriptor_types_test_90bf5b8a360ba076 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcf, 0x8b, 0xda, 0x40,
	0x14, 0xae, 0x2d, 0x9a, 0xe4, 0xa9, 0x69, 0x1c, 0x28, 0x58, 0xa4, 0x54, 0xe6, 0x52, 0x11, 0x0d,
	0x1a, 0xc5, 0x43, 0x0f, 0x2d, 0x0a, 0xbb, 0xb0, 0xb0, 0x97, 0x8d, 0xee, 0x5e, 0xc3, 0x86, 0xcc,
	0x9a, 0x80, 0x49, 0xc4, 0x19, 0xd9, 0xcd, 0x7f, 0xbf, 0xcc, 0x9b, 0x89, 0x46, 0xc1, 0x93, 0xf3,
	0xf9, 0xfd, 0x98, 0xf9, 0x5e, 0x1e, 0x38, 0xa2, 0xd8, 0x33, 0x1e, 0x08, 0xc6, 0x85, 0xbb, 0x3f,
	0xe4, 0x22, 0x27, 0x06, 0xfe, 0x24, 0x11, 0x1d, 0x43, 0x6b, 0x9d, 0x64, 0xdb, 0x1d, 0x5b, 0x8b,
	0x43, 0x92, 0x6d, 0xc9, 0x2f, 0x00, 0x11, 0xb3, 0x80, 0x23, 0xea, 0xd6, 0xfa, 0xb5, 0x81, 0xe5,
	0x5b, 0x22, 0xd6, 0x34, 0x5d, 0x01, 0x6c, 0xde, 0x73, 0x05, 0x38, 0xf9, 0x09, 0xa6, 0x12, 0x06,
	0x53, 0x2d, 0x35, 0x14, 0x9e, 0x56, 0x28, 0xaf, 0xfb, 0xb5, 0x4a, 0x79, 0x74, 0x08, 0x4d, 0x75,
	0xe5, 0x43, 0x26, 0x66, 0x1e, 0xe9, 0x81, 0xcc, 0x0f, 0x12, 0x09, 0x30, 0xa5, 0xee, 0x9b, 0x22,
	0x56, 0x24, 0xfd, 0x03, 0xa0, 0xb4, 0xab, 0x3c, 0xdf, 0xc9, 0x50, 0x29, 0x0d, 0xf3, 0x7c, 0x87,
	0x4a, 0xd3, 0x37, 0x44, 0x8c, 0x14, 0x9d, 0x40, 0x5b, 0x09, 0xef, 0x93, 0x0f, 0x16, 0xcd, 0x3c,
	0xf2, 0x1b, 0x9a, 0x52, 0xfb, 0xa6, 0x20, 0xca, 0x0d, 0x5f, 0x76, 0xd3, 0x82, 0x2b, 0xc7, 0x62,
	0x7e, 0xe1, 0x58, 0xcc, 0xd1, 0xd1, 0x38, 0x3b, 0x16, 0x73, 0x3a, 0x06, 0xdb, 0x67, 0x7b, 0xf6,
	0x2a, 0x58, 0xa4, 0xa7, 0xd5, 0x03, 0x2b, 0x2d, 0xce, 0xc3, 0xfa, 0x36, 0xb0, 0x7c, 0x33, 0x2d,
	0xf4, 0xac, 0x46, 0xd0, 0x2e, 0xe5, 0xa7, 0xa6, 0x69, 0xa1, 0x8a, 0x72, 0x54, 0xd7, 0xa5, 0x1a,
	0x39, 0x4e, 0xff, 0x96, 0x4d, 0xef, 0xb2, 0x63, 0x4a, 0x46, 0xaa, 0x29, 0xcb, 0x8e, 0x29, 0x3e,
	0xc4, 0xf6, 0x3a, 0xae, 0xfe, 0x64, 0xee, 0x86, 0x71, 0x21, 0x45, 0x58, 0x5e, 0x1e, 0xe8, 0x3f,
	0x68, 0x95, 0x37, 0xa1, 0xdb, 0x55, 0x23, 0x95, 0x6e, 0x7e, 0xdb, 0x6e, 0x6a, 0x3b, 0xa7, 0x4f,
	0x60, 0xeb, 0xbb, 0xd3, 0x90, 0x45, 0x11, 0x8b, 0xc8, 0x7f, 0x70, 0x64, 0x31, 0xfc, 0xb3, 0xba,
	0x0c, 0x4d, 0xef, 0xc7, 0x29, 0xa8, 0xba, 0x37, 0xbe, 0x9d, 0x16, 0x55, 0x4c, 0x9f, 0xc1, 0x39,
	0x3d, 0xa9, 0x0c, 0x5d, 0x42, 0xe7, 0x3a, 0x54, 0xcd, 0xe1, 0x66, 0xea, 0xf7, 0xcb, 0x54, 0x7e,
	0xde, 0x9d, 0x55, 0x21, 0x18, 0x2f, 0x77, 0x27, 0x94, 0x00, 0xdf, 0xd7, 0xc2, 0x56, 0x48, 0x0e,
	0xfb, 0x60, 0x96, 0x5d, 0x89, 0x05, 0xf5, 0x97, 0xe5, 0x63, 0x30, 0x71, 0xbe, 0x94, 0xc7, 0xa9,
	0x53, 0x0b, 0x1b, 0x78, 0xe9, 0xec, 0x33, 0x00, 0x00, 0xff, 0xff, 0x1e, 0xaf, 0xbe, 0x34, 0x20,
	0x03, 0x00, 0x00,
}
